DROP FUNCTION ENDCODEPASS (VARCHAR (), VARCHAR ());

CREATE FUNCTION ENDCODEPASS(USERID VARCHAR(8),PASS VARCHAR(8)) 
     RETURNS VARCHAR(100)
     CCSID ASCII
BEGIN ATOMIC
     DECLARE ENDCODE VARCHAR(100) DEFAULT '';
	 DECLARE USERLENGTH,USERLENGTH2,PASSLENGTH,VALUE1,VALUE2,I,J INTEGER DEFAULT 0;
     SET (USERLENGTH) = (LENGTH(USERID));
     SET (USERLENGTH2) = (LENGTH(USERID));
     SET (VALUE1) = (LENGTH(USERID));
     WHILE USERLENGTH > 0 DO
        SET (I) = (I+1);
		SET (VALUE1) = (VALUE1+(ASCII(SUBSTR(USERID,I,1))*I)+USERLENGTH2);
		SET (USERLENGTH) = (USERLENGTH-1);
     END WHILE;
     
     SET (PASSLENGTH) = (LENGTH(PASS));
     WHILE PASSLENGTH > 0 DO
        SET (J) = (J+1);
		SET (VALUE2) = (VALUE1+(ASCII(SUBSTR(PASS,J,1))+J));
		SET (ENDCODE) = (TRIM(ENDCODE)||TRIM(CHAR(VALUE2))||CHR(127));
		SET (PASSLENGTH) = (PASSLENGTH-1);
     END WHILE;
     SET (ENDCODE) = (CHR(127)||TRIM(ENDCODE));
     RETURN ENDCODE;
END;