DROP VIEW VWSTKCARD;

CREATE VIEW  VWSTKCARD(LOCAT,STRNO,INDESC,TYPEIN,REFNOIN,REFDTIN,OUTDESC, TYPEOUT,REFNOOUT,REFDTOUT,FLAG,CURSTAT,CRCOST,DISCT,NETCOST,CRVAT,TOTCOST,TADDCOST, 
                       TYPECOD,MODELCOD,BAABCOD,GCODE,COLORCOD,REGNO,MANUYR,STAT,LOCATPARK) 
AS
SELECT A.LOCAT, A.STRNO,A.INDESC,A.TYPEIN,A.REFNOIN,A.REFDTIN,A.OUTDESC, A.TYPEOUT,A.REFNOOUT,A.REFDTOUT,A.FLAG,A.CURSTAT,A.CRCOST,A.DISCT,A.NETCOST,A.CRVAT,
       A.TOTCOST, A.TADDCOST, I.TYPECOD,I.MODELCOD,I.BAABCOD,I.GCODE,I.COLORCOD,I.REGNO,I.MANUYR,A.STAT,A.LOCATPARK
FROM STKCARD A  , INVTRAN I  WHERE A.STRNO=I.STRNO;

