DROP TABLE MAINMENU;

CREATE TABLE MAINMENU
	(
	IDNO      INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ),
	SYSTEMCOD VARCHAR (10) NOT NULL,
	MENUCODE  VARCHAR (10) NOT NULL,
	MENUNAME  VARCHAR (100),
	LEVAL     INTEGER DEFAULT 1,
	MENUGRP   VARCHAR (10) DEFAULT '',
	ACTIVE    CHARACTER (1) DEFAULT 'Y',
	SORT	  INTEGER DEFAULT 0,
	CONSTRAINT PK_MAINMENU PRIMARY KEY (IDNO)
	);

DROP TABLE USERMENU;

CREATE TABLE USERMENU
	(
	IDNO     INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ),
	USERID   VARCHAR (10) NOT NULL,
	MENUCODE VARCHAR (10) NOT NULL,
	M_ACCESS CHARACTER (1) DEFAULT 'Y',
	M_EDIT   CHARACTER (1) DEFAULT 'Y',
	M_INSERT CHARACTER (1) DEFAULT 'Y',
	M_DELETE CHARACTER (1) DEFAULT 'Y',
	CONSTRAINT PK_USERMENU PRIMARY KEY (IDNO),
	FOREIGN KEY (USERID) REFERENCES PASSWRD (USERID)
	);
	
DROP TRIGGER AFTINS_MAINMENU;

CREATE TRIGGER AFTINS_MAINMENU
AFTER INSERT ON MAINMENU REFERENCING NEW AS N FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	INSERT INTO USERMENU (USERID, MENUCODE)
    SELECT B.USERID, A.MENUCODE
    FROM MAINMENU A,PASSWRD B
    WHERE A.MENUCODE = N.MENUCODE;
END;

DROP TRIGGER AFTDEL_MAINMENU;

CREATE TRIGGER AFTDEL_MAINMENU
AFTER DELETE ON MAINMENU REFERENCING OLD AS O FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
    DELETE USERMENU WHERE MENUCODE = O.MENUCODE;
END;