INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET000', 'กำหนดข้อมูลระบบ', 1, 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK000', 'ระบบสต็อกสินค้า', 1, 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL000', 'ระบบการขายสินค้า', 1, 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'FIN000', 'ระบบการรับชำระ', 1, 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'AR000', 'ระบบลูกหนี้', 1, 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX000', 'ระบบภาษี', 1, 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'ADMIN000', 'ระบบความปลอดภัย', 1, 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP1000', 'รายงานระบบสต็อกสินค้า', 1, 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2000', 'รายงานระบบการขาย', 1, 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP3000', 'รายงานระบบรับชำระ', 1, 'Y', 10);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4000', 'รายงานระบบลูกหนี้', 1, 'Y', 11);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP5000', 'รายงานระบบภาษี', 1, 'Y', 12);

/* กำหนดข้อมูลระบบ  Level 2*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET001', 'กำหนดรายละเอียดสินค้า', 2, 'SET000', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET002', 'กำหนดแคมเปญ', 2, 'SET000', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET003', 'กำหนดแคมเปญกิจกรรมสนับสนุน', 2, 'SET000', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET004', 'กำหนดข้อมูลลูกหนี้', 2, 'SET000', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET005', 'กำหนดข้อมูลระบบการเงิน', 2, 'SET000', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET006', 'กำหนดข้อมูลบริษัทที่ติดต่อ', 2, 'SET000', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET007', 'กำหนดข้อมูลเบื้องต้นของระบบ', 2, 'SET000', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET008', 'กำหนดข้อมูล Data Center', 2, 'SET000', 'Y', 8);

/* กำหนดรายละเอียดสินค้า  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET101', 'กำหนดยี่ห้อสินค้า', 3, 'SET001', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET102', 'กำหนดรุ่นสินค้า', 3, 'SET001', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET103', 'กำหนดแบบสินค้า', 3, 'SET001', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET104', 'กำหนดสีสินค้า', 3, 'SET001', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET105', 'กำหนดกลุ่มสินค้า', 3, 'SET001', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET106', 'กำหนดสถานะทางทะเบียน', 3, 'SET001', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET107', 'กำหนดรหัสอุปกรณ์เสริม', 3, 'SET001', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET108', 'กำหนดรหัสอุปกรณ์เสริมสาขา', 3, 'SET001', 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET109', 'กำหนดอุปกรณ์ตกแต่ง', 3, 'SET001', 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET110', 'กำหนดชุดแต่ง', 3, 'SET001', 'Y', 10);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET111', 'กำหนดรหัส Fleet', 3, 'SET001', 'Y', 11);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET112', 'กำหนดสถานะ Booking', 3, 'SET001', 'Y', 12);

/* กำหนดข้อมูลลูกหนี้  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET401', 'กำหนดสถานะสัญญา', 3, 'SET004', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET402', 'กำหนดสาเหตุการยึด', 3, 'SET004', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET403', 'กำหนดสาเหตุหนี้สูญ', 3, 'SET004', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET404', 'กำหนดกลุ่มลูกหนี้', 3, 'SET004', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET405', 'กำหนดกลุ่มอาชีพลูกหนี้', 3, 'SET004', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET406', 'กำหนดอาชีพลูกนี้', 3, 'SET004', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET407', 'กำหนดแหล่งที่มาลูกค้า', 3, 'SET004', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET408', 'กำหนดรหัสตำบล', 3, 'SET004', 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET409', 'กำหนดรหัสอำเภอ', 3, 'SET004', 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET410', 'กำหนดรหัสจังหวัด', 3, 'SET004', 'Y', 10);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET411', 'กำหนดรหัสไปรษณีย์', 3, 'SET004', 'Y', 11);

/* กำหนดข้อมูลระบบการเงิน  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET501', 'กำหนดประเภทการชำระเงิน', 3, 'SET005', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET502', 'กำหนดรหัสการรับชำระเงิน', 3, 'SET005', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET503', 'กำหนดรหัสธนาคาร', 3, 'SET005', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET504', 'กำหนดเลขที่บัญชีธนาคาร', 3, 'SET005', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET505', 'กำหนดสาเหตุการคืนเช็ค', 3, 'SET005', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET506', 'กำหนดวิธีการชำระเงิน', 3, 'SET005', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET507', 'กำหนดกิจกรรมการขาย', 3, 'SET005', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET508', 'กำหนดรหัสสาเหตุการลหนี้', 3, 'SET005', 'Y', 8);

/* กำหนดข้อมูลบริษัทที่ติดต่อ  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET601', 'กำหนดบริษัทไฟแนนซ์', 3, 'SET006', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET602', 'กำหนดบริษัทประกันภัย', 3, 'SET006', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET603', 'กำหนดบริษัทเจ้าหนี้', 3, 'SET006', 'Y', 3);

/* กำหนดข้อมูลเบื้องต้นของระบบ  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET701', 'กำหนดค่าคงที่ระบบ', 3, 'SET007', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET702', 'กำหนดข้อมูลสาขา', 3, 'SET007', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET703', 'กำหนดข้อมูลสถานที่จอด', 3, 'SET007', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET704', 'กำหนดหมวดหมู่เอกสาร', 3, 'SET007', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET705', 'กำหนดรหัสพนักงาน', 3, 'SET007', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET706', 'กำหนดรหัสแผนก', 3, 'SET007', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET707', 'กำหนดอัตราภาษี', 3, 'SET007', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET708', 'กำหนดส่วนลดปิดบัญชี', 3, 'SET007', 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET709', 'กำหนดอัตราเบี้ยปรับ MRR', 3, 'SET007', 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET710', 'กำหนด Running เอกสาร', 3, 'SET007', 'Y', 10);

/* กำหนดข้อมูล Data Center  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET801', 'กำหนดช่องทางที่สะดวกติดต่อ', 3, 'SET008', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET802', 'กำหนดหัวข้อการโทรติดต่อ', 3, 'SET008', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET803', 'กำหนดสถานะการติดต่อ', 3, 'SET008', 'Y', 3);

/* ระบบสต็อกสินค้า Level 2*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK001', 'โหลดข้อมูลสต็อกจาก DDMS', 2, 'STK000', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK002', 'บันทึกรับสินค้าเข้าสต็อก', 2, 'STK000', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK003', 'บันทึกรับอุปกรณ์เสริมเข้าสต็อก', 2, 'STK000', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK004', 'บันทึกรับอุปกรณ์ตกแต่ง', 2, 'STK000', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK005', 'ปรับปรุงสินค้าเข้าสต็อก', 2, 'STK000', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK006', 'บันทึกโอนย้ายสินค้าระหว่างสาขา', 2, 'STK000', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK007', 'บันทึกโอนย้ายรถเป็นสินทรัพย์', 2, 'STK000', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK008', 'บันทึกสถานที่จอดรถ', 2, 'STK000', 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK009', 'สอบถามอุปกรณ์เสริมคงเหลือ', 2, 'STK000', 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK010', 'สอบถามสินค้าคงเหลือ ณ วันที่', 2, 'STK000', 'Y', 10);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK011', 'สอบถามรายละเอียดสินค้า', 2, 'STK000', 'Y', 11);

/* ระบบการขายสินค้า Level 2*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL001', 'บันทึกประวัติลูกค้าคาดหวัง', 2, 'SAL000', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL002', 'บันทึกประวัติลูกค้า/ผู้ค้ำประกัน', 2, 'SAL000', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL003', 'บันทึกข้อมูล A-Card', 2, 'SAL000', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL004', 'บันทึกการจองสินค้า', 2, 'SAL000', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL005', 'บันทึกระบุเลขตัวถัง Matching', 2, 'SAL000', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL006', 'บันทึกข้อมูลขายสินค้าเงินสด', 2, 'SAL000', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL007', 'บันทึกข้อมูลขายผ่อนเช่าซื้อ', 2, 'SAL000', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL008', 'บันทึกข้อมูลขายส่งไฟแนนซ์', 2, 'SAL000', 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL009', 'บันทึกข้อมูลขายส่งเอเย่นต์', 2, 'SAL000', 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL010', 'บันทึกสรุปค่ารถจากบริษัทเงินทุน', 2, 'SAL000', 'Y', 10);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL011', 'บันทึกต้นทุนการขายรถ', 2, 'SAL000', 'Y', 11);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL012', 'สอบถามประวัติลูกค้า', 2, 'SAL000', 'Y', 12);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL013', 'สอบถามข้อมูลการขายรถ', 2, 'SAL000', 'Y', 13);

/* ระบบการรับชำระ Level 2*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'FIN001', 'ระบบการรับชำระเงิน', 2, 'FIN000', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'FIN002', 'ระบบควบคุมเช็ค', 2, 'FIN000', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'FIN003', 'ปรับปรุงการรับชําระและลูกหนี้', 2, 'FIN000', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'FIN004', 'ยกเลิกการรับชําระคางวด', 2, 'FIN000', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'FIN005', 'ออกใบเสร็จรบเงินจองไฟแนนซ์', 2, 'FIN000', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'FIN006', 'บันทึกเงินโอนไมทราบที่มา', 2, 'FIN000', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'FIN007', 'บันทึกรับชําระเงินอื่น ๆ', 2, 'FIN000', 'Y', 7);

/* ระบบควบคุมเช็ค  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'FIN201', 'ออกใบรับเช็ค', 3, 'FIN002', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'FIN202', 'บันทึกเช็ค Pay In', 3, 'FIN002', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'FIN203', 'บันทึกเช็คผ่าน', 3, 'FIN002', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'FIN204', 'บันทึกเช็คคืน', 3, 'FIN002', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'FIN205', 'ยกเลิกเช็คผ่าน', 3, 'FIN002', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'FIN206', 'ยกเลิกเช็คคืน', 3, 'FIN002', 'Y', 6);

/* ระบบลูกหนี้ Level 2*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'AR001', 'บันทึกรถยึดรอไถ่ถอน', 2, 'AR000', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'AR002', 'บันทึกไถ่ถอนรถยึด', 2, 'AR000', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'AR003', 'บันทึกรถยึดเข้าสต็อก', 2, 'AR000', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'AR004', 'บันทึกข้อมูลหนี้สูญ', 2, 'AR000', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'AR005', 'บันทึกเปลี่ยนแปลงผู้เช่าซื้อ', 2, 'AR000', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'AR006', 'แก้ไขสัญญาเช่าซื้อ', 2, 'AR000', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'AR007', 'บันทึกผลการตามหนี้', 2, 'AR000', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'AR008', 'บันทึกลูกหนี้อื่น ๆ', 2, 'AR000', 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'AR009', 'บันทึกการออกจดหมายทวงหนี้', 2, 'AR000', 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'AR010', 'สอบถามข้อมูลเช่าซื้อ', 2, 'AR000', 'Y', 10);

/* ระบบภาษี Level 2*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX001', 'ออกใบกากบภาษีค่างวดก่อนดิว', 2, 'TAX000', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX002', 'ออกใบกากบภาษีค่างวดตามดิว', 2, 'TAX000', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX003', 'บันทึกใบเพิ่มหนี้ภาษี', 2, 'TAX000', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX004', 'บันทึกใบลดหนี้ภาษีซื้อ', 2, 'TAX000', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX005', 'บันทึกใบลดหนี้ภาษีขาย', 2, 'TAX000', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX006', 'แก้ไขรายการใบกำกับภาษี', 2, 'TAX000', 'Y', 6);

/* ระบบภาษี  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX301', 'ใบเพิ่มหนี้ภาษีรถยนต์', 3, 'TAX003', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX302', 'ใบเพิ่มหนี้ภาษีอื่น ๆ', 3, 'TAX003', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX401', 'ใบลดหนี้ภาษีซื้อทั้งคัน', 3, 'TAX004', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX402', 'ใบลดหนี้ภาษีซื้อบางส่วน', 3, 'TAX004', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX501', 'ใบลดหนี้ภาษีขายส่งไฟแนนซ์ทั้งคัน', 3, 'TAX005', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX502', 'ใบลดหนี้ภาษีขายส่งไฟแนนซ์บางส่วน', 3, 'TAX005', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX503', 'ใบลดหนี้ภาษีขายสดทั้งคัน', 3, 'TAX005', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX504', 'ใบลดหนี้ภาษีขายสดบางส่วน', 3, 'TAX005', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX505', 'ใบลดหนี้ภาษีขายส่งเอเย่นต์', 3, 'TAX005', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX506', 'ใบลดหนี้ภาษีขายอื่น ๆ', 3, 'TAX005', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX601', 'แก้ไขชื่อในใบกำกับ', 3, 'TAX006', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'TAX602', 'ยกเลิกใบกำกับภาษีค่างวด', 3, 'TAX006', 'Y', 2);

/* ระบบความปลอดภัย Level 2*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'ADMIN001', 'กำหนด User Id เข้าใช้ระบบ', 2, 'ADMIN000', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'ADMIN002', 'เปลี่ยนรหัสผ่าน', 2, 'ADMIN000', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'ADMIN003', 'กำหนดสิทธิการใช้งาน', 2, 'ADMIN000', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'ADMIN004', 'คัดลอกสิทธิการใช้งาน', 2, 'ADMIN000', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'ADMIN005', 'ตรวจสอบการใช้งานระบบ', 2, 'ADMIN000', 'Y', 5);

/* รายงานระบบสต็อกสินค้า Level 2*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP1001', 'รับสินค้าเข้าสต็อก', 2, 'RP1000', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP1002', 'รับสินค้าเพื่อดูต้นทุน', 2, 'RP1000', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP1003', 'โอนย้ายสินค้าระหว่างสาขา', 2, 'RP1000', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP1004', 'ต้นทุนสินค้าคงเหลือ', 2, 'RP1000', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP1005', 'สินค้าคงเหลือเพื่อตรวจสอบ', 2, 'RP1000', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP1006', 'สินค้าคงเหลือ ณ วันที่', 2, 'RP1000', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP1007', 'ปรับปรุงสต็อกสินค้า', 2, 'RP1000', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP1008', 'รายละเอียดชุดแต่ง', 2, 'RP1000', 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP1009', 'การเบิกอุปกรณ์ตกแต่ง', 2, 'RP1000', 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP1010', 'การบันทึกสถานที่จอด', 2, 'RP1000', 'Y', 10);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP1011', 'โอนรถเป็นสินทรัพย์', 2, 'RP1000', 'Y', 11);

/* รายงานระบบการขาย Level 2*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2001', 'รายงานการขายเพื่อตรวจสอบ', 2, 'RP2000', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2002', 'รายงานการขายเพื่อลงบัญชี', 2, 'RP2000', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2003', 'วิเคราะห์ข้อมูลการขาย', 2, 'RP2000', 'Y', 3);

/* รายงานการขายเพื่อตรวจสอบ  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2101', 'ขายสินค้าเงินสด', 3, 'RP2001', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2102', 'ขายส่งไฟแนนซ์', 3, 'RP2001', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2103', 'ขายผ่อนเช่าซื้อ', 3, 'RP2001', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2104', 'ขายส่งเอเยนต์', 3, 'RP2001', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2105', 'A-Card ตามวันที่บันทึก', 3, 'RP2001', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2106', 'ประวัติลูกค้า', 3, 'RP2001', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2107', 'การ์ดลูกหนี้เพื่อบัญชี', 3, 'RP2001', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2108', 'ฟอร์มใบปะหน้ารถ', 3, 'RP2001', 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2109', 'Fleet Form', 3, 'RP2001', 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2110', 'แจ้งขายรถ', 3, 'RP2001', 'Y', 10);

/* รายงานการขายเพื่อตรวจสอบ  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2201', 'ขายสินค้าเงินสด', 3, 'RP2002', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2202', 'ขายส่งไฟแนนซ์', 3, 'RP2002', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2203', 'ขายผ่อนเช่าซื้อ', 3, 'RP2002', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2204', 'ขายส่งเอเยนต์', 3, 'RP2002', 'Y', 4);

/* วิเคราะห์ข้อมูลการขาย  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2301', 'การขายตามรุ่น สี สินค้า', 3, 'RP2003', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2302', 'การขายแยกตามประเภทการขาย', 3, 'RP2003', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP2303', 'ต้นทุนกำไรจากการขายต่อคัน', 3, 'RP2003', 'Y', 3);

/* รายงานระบบรับชำระ Level 2*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP3001', 'การรับชำระเงินประจำวัน', 2, 'RP3000', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP3002', 'ลูกหนี้เช่าซื้อปิดบัญชี', 2, 'RP3000', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP3003', 'การ์ดลูกหนี้และการรับชำระ', 2, 'RP3000', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP3004', 'การรับชำระตามเลขที่สัญญา', 2, 'RP3000', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP3005', 'ยกเลิกการรับชำระเงิน', 2, 'RP3000', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP3006', 'สรุปการรับชำระเงิน', 2, 'RP3000', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP3007', 'การรับเช็ค', 2, 'RP3000', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP3008', 'สถานะเช็ค', 2, 'RP3000', 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP3009', 'การรับเงินค่ารถจากไฟแนนซ์', 2, 'RP3000', 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP3010', 'เงินโอนไม่ทราบที่มา', 2, 'RP3000', 'Y', 10);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP3011', 'การคืนเงินจองรถยนต์', 2, 'RP3000', 'Y', 11);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP3012', 'บอร์ดควบคุมยอดหนี้ค้างชำระ บ.ไฟแนนซ์', 2, 'RP3000', 'Y', 12);

/* รายงานระบบลูกหนี้ Level 2*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4001', 'ลูกหนี้คงเหลือ', 2, 'RP4000', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4002', 'ตรวจสอบลูกหนี้เช่าซื้อ', 2, 'RP4000', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4003', 'วิเคราะห์ข้อมูลลูกหนี้', 2, 'RP4000', 'Y', 3);

/* ลูกหนี้คงเหลือ  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4101', 'ลูกหนี้คงเหลือขายสด', 3, 'RP4001', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4102', 'ลูกหนี้คงเหลือขายส่งไฟแนนซ์', 3, 'RP4001', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4103', 'ลูกหนี้คงเหลือขายส่งเอเยนต์', 3, 'RP4001', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4104', 'ลูกหนี้คงเหลือขายผ่อนเช่าซื้อ', 3, 'RP4001', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4105', 'สรุปลูกหนี้คงเหลือ', 3, 'RP4001', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4106', 'สรุปลูกหนี้อื่น ๆ คงเหลือ', 3, 'RP4001', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4107', 'ลูกหนี้ค้างชำระเงินดาวน์', 3, 'RP4001', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4108', 'ลูกหนี้ค้างชำระเบี้ยปรับ', 3, 'RP4001', 'Y', 8);

/* ตรวจสอบลูกหนี้เช่าซื้อ  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4201', 'รถยึดและไถ่ถอนรถยึด', 3, 'RP4002', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4202', 'บันทึกหนี้สูญ', 3, 'RP4002', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4203', 'ลูกหนี้ค้างชำระ X งวด', 3, 'RP4002', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4204', 'ลูกหนี้ครบกำหนดชำระ', 3, 'RP4002', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4205', 'ลูกหนี้ครบกำหนดสัญญา', 3, 'RP4002', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4206', 'ลูกหนี้ชำระเงินครบแล้ว', 3, 'RP4002', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4207', 'บันทึกผลการตามหนี้', 3, 'RP4002', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4208', 'การเปลี่ยนแปลงผู้เช่าซื้อ', 3, 'RP4002', 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4209', 'จดหมายยืนยันยอดลูกหนี้', 3, 'RP4002', 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4210', 'หนังสือบอกเลิกสัญญา', 3, 'RP4002', 'Y', 10);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4211', 'หนังสือแจ้งเตือนให้ชำระค่างวด', 3, 'RP4002', 'Y', 11);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4212', 'หนังสือแจ้งการขายทอดตลาด', 3, 'RP4002', 'Y', 12);

/* วิเคราะห์ข้อมูลลูกหนี้  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4301', 'สรุปสถานะลูกค้า', 3, 'RP4003', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP4302', 'สรุปยอดเงินค้างชำระ', 3, 'RP4003', 'Y', 2);

/* รายงานระบบภาษี Level 2*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP5001', 'ภาษีซื้อ', 2, 'RP5000', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP5002', 'ภาษีขาย', 2, 'RP5000', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP5003', 'ฟอร์มใบกำกับ', 2, 'RP5000', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP5004', 'เสียภาษีอากรแสตมป์', 2, 'RP5000', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP5005', 'ตรวจสอบใบกำกับภาษีค่างวด', 2, 'RP5000', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP5006', 'ภาษีค่างวดค้างชำระ', 2, 'RP5000', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'RP5007', 'การยกเลิกภาษี', 2, 'RP5000', 'Y', 7);